# Generated by Django 4.0.5 on 2022-07-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('note', models.TextField(max_length=200)),
            ],
        ),
    ]
