# Generated by Django 4.0.5 on 2022-07-22 04:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mynotes_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='timedate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2022, 7, 22, 10, 21, 3, 286408)),
        ),
    ]
