# Generated by Django 4.0.5 on 2022-07-22 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_mynotes_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='timedate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 10, 26, 10, 888440)),
        ),
    ]
