# Generated by Django 4.0.5 on 2022-07-22 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mynotes_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='timedate',
            field=models.DateField(default=datetime.date(2022, 7, 22)),
        ),
    ]
