# Generated by Django 4.0.5 on 2022-07-22 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_mynotes_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='timedate',
            field=models.DateField(default=datetime.datetime(2022, 7, 22, 10, 45, 2, 906905)),
        ),
    ]
