# Generated by Django 4.0.5 on 2022-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_mynotes_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='timedate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
